-- Web Push (PWA) subscriptions — one row per browser/device push subscription,
-- tied to the DIDA user who registered it on that device. The API manages rows
-- (subscribe/unsubscribe at the authenticated boundary); the notify adapter
-- reads them to deliver `notify` commands as Web Push messages and deletes any
-- subscription the push service reports gone (HTTP 404/410).
--
-- The VAPID application keypair lives in app_settings (webpush_vapid_public /
-- webpush_vapid_private, private Fernet-encrypted) — generated by the API on
-- first boot, never rotated silently (that would strand every subscription).
CREATE TABLE IF NOT EXISTS push_subscriptions (
    id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    endpoint   TEXT NOT NULL UNIQUE,
    p256dh     TEXT NOT NULL,
    auth       TEXT NOT NULL,
    user_agent TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_ok_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_push_subscriptions_user ON push_subscriptions (user_id);
