#!/usr/bin/env sh
# Materialise the app revision into revision.json at the repo root.
#
# Single source of truth = git. MAJOR.MINOR come from ./VERSION (hand-bumped for
# a feature milestone); the patch is the commit count, so the number climbs on
# every commit/push automatically — no manual bookkeeping. The short SHA + branch
# + commit date pin the exact build.
#
# revision.json is git-derived and NEVER committed (it's in .gitignore). It is
# regenerated by the git hooks (post-commit / post-merge / pre-push) and read at
# runtime by the API (GET /version) — bind-mounted read-only into the container.
set -eu

# Resolve the repo root so this works no matter where a hook fires from.
ROOT="$(git rev-parse --show-toplevel 2>/dev/null || echo .)"
cd "$ROOT"

BASE="$(tr -d ' \t\n\r' < VERSION 2>/dev/null || echo 0.0)"
COUNT="$(git rev-list --count HEAD 2>/dev/null || echo 0)"
SHA="$(git rev-parse --short=8 HEAD 2>/dev/null || echo unknown)"
BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
COMMITTED_AT="$(git log -1 --format=%cI 2>/dev/null || echo unknown)"
if git diff --quiet --ignore-submodules HEAD 2>/dev/null; then DIRTY=false; else DIRTY=true; fi

cat > revision.json <<EOF
{
  "version": "${BASE}.${COUNT}",
  "base": "${BASE}",
  "count": ${COUNT},
  "sha": "${SHA}",
  "branch": "${BRANCH}",
  "committed_at": "${COMMITTED_AT}",
  "dirty": ${DIRTY}
}
EOF
